
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module mcu(

	//////////// CLOCK //////////
	input CLK,

	//////////// 7-segment decoder //////////
	output [6:0] HEX0,
	output [6:0] HEX1,
	output [6:0] HEX2,
	output [6:0] HEX3,
	
	//////////// LED /////////////
	output [9:0] LED,
	
	//////////// SWITCH //////////
	input [9:0] SW,
	
	//////////// BUTTON //////////
	input [2:0] BTN
	
);
//*******************************//
	logic [7:0] port_b;
	// add module here
	cpu cpu_test(
			.clk(CLK),
			.reset(~BTN[1]),
			.port_b_out(port_b)
	);
	sevenSegmentDecoder sevenSegmentDecoder_0(
		.signal(HEX0),
		.num(port_b[3:0])
	);

//*******************************//

endmodule
